log.exception.runtime.aborted=agent aborted due to an unexpected error
log.agent.start=agent started: {0}
log.agent.finish=agent finished: {0}
log.search=search called with parameters: {0}
log.delete.trigger=trigger cancelled
log.init.agent=agent initialized: {0}
log.next.agent.notSet=entry for agent for status NOT_SET: {0}
log.next.agent.notset.init=new status for agent with status NOT_SET: {0}
log.next.agent.lastEntry=last entry for agent: {0}
log.next.agent.lastEntry.init=last entry for agent initialized: {0}
log.next.agent.created=new agent created: {0}
log.next.agent.trigger.current=crontrigger set for current agent: {0}
log.next.agent.trigger.new=crontrigger set for new agent: {0}
log.search.validate.limit=invalid max limit vor search: {0} - reset with {1}
log.search.validate.status=status for search: {0} - flag: {1}
log.search.validate.executor=executor for search: {0} - flag: {1}
log.search.validate.to.startTime=to start time for search: {0} - flag: {1}
log.search.validate.from.startTime=from start time for search: {0} - flag: {1}
log.search.validate.end=start search for flag {0} and with limit {1}
protocol.arguments.none=no arguments set
protocol.arguments.set=arguments are set
